### ISSUE TITLE
Output folder of processed files

### ISSUE THREAD

**Issue by simube** [seiz/novaless#1]
Thanks for adding this extension!
It would be very nice to have an option to output the processed files to another folder.

**Comment by seiz** [comment]
Hi,
since Nova-Extensions only have global Preferences (not Project, or File specific ones), i would not know how to do this in a manner which makes sense and where the user can define which folder to use…
So i am afraid, this is out of scope for such an extension.

**Comment by simube** [comment]
Ok, I see... a relative path would be perfect for me, but then it'll be the same for every project...
Thanks for clarification!

**Comment by seiz** [comment]
Yes, exactly. Thus it probably makes more sense to handle this with a specialised tool. 
I use https://codekitapp.com for such things…

**Comment by simube** [comment]
Hi again.

I tried a bit myself and saw that there is an easy way to set a project specific preference with "configWorkspace" in the extension.json.
I struggle a bit to set the correct output path as the paths provided by Nova sometimes start with "/Volumes/HDD..." and sometimes with "/Users/myname/..."
But it should be possible.

Screenshot of the project settings:
![CleanShot 2020-09-18 at 19 44 25](https://user-images.githubusercontent.com/7550745/93628770-68d87800-f9e7-11ea-9548-97d16852b7b5.png)

**Comment by seiz** [comment]
Hi Simon,

this is great. Didn't know about `configWorkspace `. Since this offers per Project Preferences, we won't even need relative paths. I'll look into this and try to implement it.

**Comment by simube** [comment]
Problem is, that you can't select a Folder with the option "path" in these preferences. Only files.
I sent a pull request with my solution.

**Comment by seiz** [comment]
@simube this is implemented now in 1.0.4 and an update has been released to the nova extensions library.

**Comment by simube** [comment]
Awesome! Thanks :)
