### ISSUE TITLE
env: node: No such file or directory

### ISSUE THREAD

**Issue by ErniePC12** [seiz/novaless#2]
I used Homebrew to install Node/NPM. 

I have lessc installed in the default /usr/local/lessc that links to /usr/local/lib/node_modules/less/bin/lessc.

I am getting the error above.

**Comment by seiz** [comment]
Hi,
the default path for the extension is `/usr/local/bin/lessc`. If you have lessc installed at a different location, you can set that location in the Extension's "Executable Path" Preference.

**Comment by ErniePC12** [comment]
I have the lessc executable located in the path /usr/local/bin.  

I can run it manually in Terminal, just not when I'm saving a document.

Is there a way I can debug this or see what errors it runs into other than the notification?

**Comment by seiz** [comment]
Did you set the Extension's preference as i suggested?
Guess in your case, you should set "Executable Path" to `/usr/local/bin/lessc`

**Comment by seiz** [comment]
Sorry, `/usr/local/bin/lessc`is the default path (didn't see that immediately), so there should not be a need to change anything. Being new to Nova myself, i do not know how to get more info about the error from within Nova. 
Could you copy the text from the error-notification or make a screenshot and attach it here?
You should probably also check permissions for `/usr/local/bin/lessc` and make sure, that everybody is allowed to execute it.

**Comment by ErniePC12** [comment]
The permissions are set properly, read and execute for everyone. I see that I could look directly at the code, I might have it write more to the console...

This is the notification that I receive.
<img width="313" alt="image" src="https://user-images.githubusercontent.com/187422/93641072-af1ede80-f9c9-11ea-8da7-e5a8eaad4c13.png">

This is the info that I get in the extension Console.
Less[16:11:52.531000] Lessc on: /Volumes/Macintosh HD/Users/Ernie/Website/css/style.less
Less[16:11:52.532000] Using lessc binary at:/usr/local/bin/lessc

**Comment by ErniePC12** [comment]
Sorry, didn't mean to close it

**Comment by seiz** [comment]
Seems like it can't find node. Possibly because it's not in your path or such. Possible solution: https://stackoverflow.com/a/26320915

**Comment by ErniePC12** [comment]
Can't write into /usr/bin, it's protected.

System Integrity Protection
https://support.apple.com/en-us/HT204899

**Comment by seiz** [comment]
There's nothing i can do about that. Maybe you could symlink /usr/local/bin instead or just install lessc as mentioned in the README. I can not change/fix an installation from within the Extension. Sorry.

**Comment by ErniePC12** [comment]
I'm still struggling on this.  I realize that I have spaces in my paths, have you tried this with a path with spaces?

Less[16:11:52.531000] Lessc on: /Volumes/Macintosh HD/Users/Ernie/Website/css/style.less
