### ISSUE TITLE
Throws error when saving Imported files.

### ISSUE THREAD

**Issue by pixahive** [seiz/novaless#4]
So I have 3 Less Files.

`Variables.less` - contains some variables like @background, @text, etc.
`Header.less` - header layouts, etc
`Main.less` - imports variables.less and header.less and has some more code.

Now, when I try to save main.less the CSS file is generated and everything works smoothly.
But, when I make changes to header.less i get errors like `@background is not defined`. 

Till now, I was using the same structure with CodeKit and did not face a problem like this.

**Comment by seiz** [comment]
Hi,
short of parsing all .less files to find out about their import relationship (and the possibly ignoring them, when a change is saved), i wouldn't know how to solve this. I am afraid, this is out of scope for a hoppy-project (used to solve my own itch) like this.

CodeKit parses the file to know their relationships and then ignores the included files and doesn't compile them on save but instead compiles the file which imports them. That would be very complicated (if possible at all) in an extension like this.

I guess, you could change the extension of your included files to e.g. ".inc", so they don't get compiled on save (which is not necessary at all. But that would of course not cause main.less to get recompiled if header.less changes. It's probably best to continue using CodeKit (which i love too) for this.

Sorry i can't help you more. If anyone has any ideas on how to solve something like this, i am all ears.
