### ISSUE TITLE
Unexpected behaviour: relative path a directory ../

### ISSUE THREAD

**Issue by studio-express** [seiz/novaless#5]
My project consists of modules and each has an Asset folder which contains LESS and CSS folders.
I give the path ../css: and the css is compiled in the root folder of the project.

** Q: How do I specify the relative path to the CSS folder? **

![less2css-opt](https://user-images.githubusercontent.com/4165508/93863667-d1b83c80-fcd4-11ea-80ea-f6c76c19b3a5.png)

**Comment by seiz** [comment]
Hi,
the Project-Preference sets the path relative to the Project, not the less-file and we only have one Preference. So i guess, what you need, can currently not be done with this Extension.
