### ISSUE TITLE
Compile to server

### ISSUE THREAD

**Issue by mjut** [seiz/novaless#6]
I would like to compile my less-file on a remote server.

As it is working fine locally, I guess this extension doesn't allow compiling remotely? 

Thanks for your help--

**Comment by seiz** [comment]
Can you provide more details, like how do you open the file in Nova? Is the server mounted as a volume and is the project also stored remotely or local…?

**Comment by mjut** [comment]
Hi Stefan,

yes – I am working directly on a remote server. Connected via SFTP, set up as a project in Nova.app.
There is no local files set up nor stored. It's all happening remotely.
(For testing: When saving a less file locally, the css is being generated as expected.)

Cheers
Stephan

**Comment by seiz** [comment]
Thanks for the clarification. I have not used Nova like that. I have to familiarize myself with that usage first, before i can say if this is even technically possible (via the NOVA-Api). I won't be able to invest a lot of time into this, however. I'll let you know.

**Comment by seiz** [comment]
Hi,

i did some research and it seems, based on the current Nova-Api, what you want is unfortunately not possible (at leas i couldn't find any hooks into the remote-upload-processing). Sorry.

**Comment by mjut** [comment]
No worries – 
Thanks for looking into it!
