### ISSUE TITLE
grid-column range gets parsed wrong

### ISSUE THREAD

**Issue by simube** [seiz/novaless#7]
Hi

Thanks for this great extension!

I just noticed, that writing:
`grid-column: 1 / 4;`
parses to:
`grid-column: .25;`

I have to separate the values to grid-column-start / grid-column-end to get it to work :)

**Comment by seiz** [comment]
Hi,

that is expected behaviour in less, because less can do calculations. "1 / 4" will devide 1 by 4 and the result is 0.25.

If you want to avoid that, you can write it escaped like this:
`grid-column: ~"1 / 4";`

See: https://lesscss.org/#escaping
