### ISSUE TITLE
Less Compile Error on remote server

### ISSUE THREAD

**Issue by pierr0t** [seiz/novaless#8]
Hello,
I'm getting this error when trying to compile remote less files, so far so good ! Problem is now that I'm getting this error when saving any file on the remote server, even an html file, a php file ... which can be annoying when working remotely on a site ...
Pierre.

**Comment by seiz** [comment]
Hi,

sorry, I don't use Nova anymore, so this Plugin is basically unmaintained. I suggest you deinstall the plugin and see if that fixes your errors.

**Comment by pierr0t** [comment]
Of course uninstalling fixes the error because it's the only less plugin I have and error started appearing right away after installing and is labelled "Less" ...
Should I/you advise Nova that plugin is not maintained anymore and that they should stop from proposing it on their pages ?
